Typescript for favorite community artists, placeholder and some more stuff
MetalDetectorRocks/metal-detector-main pull request #198
Opened 2020-08-27 13:20 UTC by hedgehog1833

This PR contains a few changes:
- Favorite community artists are fetched and displayed on homepage
- Placeholder card is shown if there are only three cards in a release row
- Only one release row is created if not enough results are present for two rows
- If this row would have more that four elements the last ones are cut
There are still some open points here. One would be that there is no placeholder if there are not enough recently followed artists. This is because we cannot use the artist placeholder because the card would have a different height as the artist cards have one row less text.
Also play around a little with the mock and put more or less releases in the list to see what happens. The placeholder layout of course is open for discussion.

2020-08-27 13:55 UTC, hedgehog1833 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Detector] Render start page cards with TypeScript](https://trello.com/c/D9Na8oxO/207-detector-render-start-page-cards-with-typescript)

2020-08-31 17:19 UTC, DanielW1987 reviewed
Can you please resize the question mark to reduce traffic? The current homepage pictures are 300x300 in size (more or less).

2020-08-31 17:45 UTC, DanielW1987 requested changes

2020-08-31 17:45 UTC, DanielW1987 commented on webapp/src/main/resources/static/ts/src/service/date-service.ts
> +    }
I would rather sort in the backend. Is there something to be said against that?

2020-08-31 17:45 UTC, DanielW1987 commented on webapp/src/main/resources/static/ts/src/service/date-service.ts
> +    }
If it's not possible why not just simple return

```typescript
return release1.releaseDate.valueOf() - release2.releaseDate.valueOf();
```

2020-08-31 17:45 UTC, DanielW1987 commented on webapp/src/main/resources/static/ts/src/service/homepage-render-service.ts
> +            response.recentReleases.length >= this.CARDS_PER_ROW - 1) {
why do we need `>=` and `-1` in combination here...?

2020-08-31 17:45 UTC, DanielW1987 commented on webapp/src/main/resources/static/ts/src/service/homepage-render-service.ts
> +            response.recentReleases.length >= this.CARDS_PER_ROW - 1) {
Maybe it's clearer to use simply 3 or introduce a new constant. 
Maybe in the future `CARDS_PER_ROW` is 8.

2020-08-31 17:45 UTC, DanielW1987 commented on webapp/src/main/resources/static/ts/src/service/homepage-render-service.ts
> +    }
Do we want a placeholder if it is 3 or less, isn't it?

2020-08-31 17:45 UTC, DanielW1987 commented on webapp/src/main/resources/static/ts/src/service/homepage-render-service.ts
> +        this.insertPlaceholder(response.recentReleases.length, recentReleasesRowElement);
this looks like a mistake

2020-08-31 17:45 UTC, DanielW1987 commented on webapp/src/main/resources/static/ts/src/service/homepage-render-service.ts
> +        }
It should be easier if you simply add the releases from the two lists to a new list first and then just iterate over that list. First add the upcoming releases and after that the recent releases. You can break the for loop after 4.

2020-09-01 21:12 UTC, hedgehog1833 commented on webapp/src/main/resources/static/ts/src/service/date-service.ts
> +    }
The problem is that the sorting only has to be done when there are so few results that we only show one row. And in one row it looks strange if both - the recent and the upcoming - releases are sorted in ascending order, as we would have something like "release A 2 days ago, release B 5 days ago, release C in 1 day, release D in 10 days". In this case I would prefer having the chronological order for all releases.
And I think that the backend shouldn't care about something like that so yeah, ordering here seems right. But also your second suggestions looks better so I'll apply that 👍

2020-09-02 06:45 UTC, hedgehog1833 commented on webapp/src/main/resources/static/ts/src/service/homepage-render-service.ts
> +    }
Yes. I still struggle with the idea of having always full rows of 4 cards. The idea to prevent that (using one row if there are too few releases) does not always work out perfectly.. But yes, I set the value to `elementCount < this.CARDS_PER_ROW`

2020-09-02 07:21 UTC, hedgehog1833 commented on webapp/src/main/resources/static/ts/src/service/date-service.ts
> +    }
As just discussed: ordering is now in the backend 😂

2020-09-05 10:55 UTC, DanielW1987 approved these changes

2020-09-05 11:26 UTC, merged