Blog backend initialsetup
MetalDetectorRocks/metal-detector-main pull request #214
Opened 2020-10-05 07:12 UTC by ReginaSchuster

Created blogpost entity, dummy posts and Rest endpoint to get all posts

2020-10-05 07:51 UTC, ReginaSchuster commented
This was compiling fine locally, but showed a Maven error in the PR. After merging the master branch into this branch and re-running it locally, I get the following error: "java: error: release version 15 not supported". Couldn't figure it out right away and will look into this again.

2020-10-28 17:51 UTC, hedgehog1833 requested changes
Looks fine, just some smaller remarks 👍  And a test for the `BlogpostRestController` is missing 😉

2020-10-28 17:51 UTC, hedgehog1833 commented on persistence/src/main/java/rocks/metaldetector/persistence/domain/blogpost/BlogpostEntity.java
> +@NoArgsConstructor
This constructor does not have to be accessible from anywhere (an import is needed for this suggestion to work).
```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED) // for hibernate and model mapper
```

2020-10-28 17:51 UTC, hedgehog1833 commented on webapp/src/main/java/rocks/metaldetector/service/blogpost/BlogpostServiceImpl.java
> +@Slf4j
I wouldn't add this if you're not logging anything.

2020-10-28 17:51 UTC, hedgehog1833 commented on persistence/src/main/java/rocks/metaldetector/persistence/domain/blogpost/BlogpostEntity.java
> +    private boolean draftFlag;
I think just `draft` would be better for a name. Otherwise the getter will be `isDrafFlag()` which sounds a bit weird.

2020-10-28 17:51 UTC, hedgehog1833 commented on persistence/pom.xml
> +        <!-- Validation -->
This dependency is not needed, see my comment in `BlogpostEntity.java`

2020-10-28 17:51 UTC, hedgehog1833 commented on persistence/src/main/java/rocks/metaldetector/persistence/domain/blogpost/BlogpostEntity.java
> +    public BlogpostEntity(@NonNull String title, @NonNull String slug, @NonNull String text,
The `@NotNull` is not necessary here. It is ensured on database level that these values are not null. Also for consistency reasons I would say that we omit them as we never used it so far.

2020-10-28 17:51 UTC, hedgehog1833 commented on persistence/src/main/java/rocks/metaldetector/persistence/domain/blogpost/BlogpostEntity.java
> +    @Size(min = 2, max = 255)
I guess using the `@Size` annotation would work, but the additional Dependency is not necessary here. `@Column` has a `length` parameter that can be overwritten if needed (default is 255) and the minimum value can be left out in my opinion.
Please also check the other member.

2020-10-28 17:51 UTC, hedgehog1833 commented on persistence/src/main/java/rocks/metaldetector/persistence/domain/blogpost/BlogpostEntity.java
> +    private String slug;
What's a slug in this context? I thought a slug is this: 🐌 😅  I guess it is the English term for the short version of an article?

2020-10-28 17:51 UTC, hedgehog1833 commented on persistence/src/main/java/rocks/metaldetector/persistence/config/bootstrap/DefaultDatabaseInitializer.java
> +            .draftFlag(true)
Maybe add one example that is no draft?

2020-10-28 17:51 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/service/blogpost/BlogpostServiceTest.java
> +public class BlogpostServiceTest implements WithAssertions {
Our naming schema so far is naming the tests for service implementations are the certain class, so this would be `BlogpostServiceImplTest`. That's nicer when you have multiple implementations (or mocks).

2021-02-27 13:52 UTC, closed without merging