Metal Detector gradle migration
MetalDetectorRocks/metal-detector-main pull request #276
Opened 2020-12-22 10:22 UTC by hedgehog1833

I migrated the Detector to gradle. Some DTOs needed a no-args constructor and I had to add an annotation somewhere but all in all it was pretty straight forward. Build time dropped from about 1:50 to less than 1:20.

2020-12-22 12:55 UTC, hedgehog1833 commented
Info for the local setup after merging this: uncheck the "Generate *.iml files...." option in your Idea Gradle settings. We don't need those.

2020-12-22 15:54 UTC, DanielW1987 reviewed
I miss the CodeCov post on this PR

2020-12-22 15:54 UTC, DanielW1987 commented on .github/workflows/deploy.yml
> +          arguments: clean test
have you checked if this creates a .jar?

2020-12-22 15:54 UTC, DanielW1987 commented on build.gradle
> +    implementation "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
do we really have to use a concrete springBootVersion? With Maven, this is managed by the parent.

2020-12-22 15:54 UTC, DanielW1987 commented on persistence/src/main/java/rocks/metaldetector/persistence/domain/token/TokenRepository.java
> +  Optional<TokenEntity> findResetPasswordToken(@Param("tokenString") String tokenString);
why do we need this?

2020-12-22 22:11 UTC, hedgehog1833 commented on persistence/src/main/java/rocks/metaldetector/persistence/domain/token/TokenRepository.java
> +  Optional<TokenEntity> findResetPasswordToken(@Param("tokenString") String tokenString);
Because otherwise the corresponding integration test fails 🤷‍♂️  The annotation explicitly says that this parameter is exchanged with the string in the query.

2020-12-22 22:12 UTC, hedgehog1833 commented on build.gradle
> +    implementation "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
I think so. In gradle there is no such thing as a parent so we have to pull the version by ourselves. But it doesn't make much difference where to write the version number, so who cares? 😉

2020-12-28 11:43 UTC, DanielW1987 commented on build.gradle
> +    implementation "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
In Butler we don't have to specify the versions explicitly either.

2020-12-28 11:50 UTC, hedgehog1833 commented on build.gradle
> +    implementation "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
Hmm that's right, it's just in the plugin there but I can't get it running without the version number here.... 🤔 I can check this again, but I'd say that's a point for later 😉

2020-12-28 11:55 UTC, DanielW1987 commented on build.gradle
> +    implementation "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
Maybe you just have to remove the `apply false`. Why is this there?

2020-12-28 12:01 UTC, hedgehog1833 commented on build.gradle
> +    implementation "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
I tried that, doesn't work.

2020-12-28 12:19 UTC, DanielW1987 approved these changes

2021-01-02 15:37 UTC, DanielW1987 requested changes
set java version also in `system.properties`

2021-01-02 15:37 UTC, DanielW1987 commented on build.gradle
> +    springSecurityVersion = "5.2.6.RELEASE"
can you please define all versions here? Now we have versions in many different places.

2021-01-04 09:38 UTC, hedgehog1833 commented on Dockerfile
> +FROM openjdk:11-stretch
Will do, but we use this one in the butler so we should change it there too.

2021-01-04 10:52 UTC, DanielW1987 approved these changes

2021-01-04 10:57 UTC, merged