fix date bugs on start page
MetalDetectorRocks/metal-detector-main pull request #302
Opened 2021-01-21 17:31 UTC by DanielW1987

2021-01-21 17:31 UTC, DanielW1987 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wrong ordering on start page](https://trello.com/c/YRHogHaI/298-wrong-ordering-on-start-page)

2021-01-21 17:32 UTC, DanielW1987 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display bug "tomorrow" on homepage](https://trello.com/c/tPAh1nKR/295-display-bug-tomorrow-on-homepage)

2021-01-21 19:33 UTC, hedgehog1833 requested changes

2021-01-21 19:33 UTC, hedgehog1833 commented on webapp/src/main/resources/static/ts/src/service/date-service.ts
> +        return dayjs(dateStr1).isBefore(dateStr2) ? -1 : dayjs(dateStr1).isBefore(dateStr2) ? 1 : 0;
```suggestion
        return dayjs(dateStr1).isBefore(dateStr2) ? -1 : dayjs(dateStr2).isBefore(dateStr1) ? 1 : 0;
```

2021-01-22 15:52 UTC, hedgehog1833 approved these changes

2021-01-22 16:10 UTC, merged