remove login wall
MetalDetectorRocks/metal-detector-main pull request #581
Opened 2022-02-05 19:01 UTC by DanielW1987

Cool...2 months of work.

2022-02-06 17:39 UTC, DanielW1987 commented
![](https://github.trello.services/images/mini-trello-icon.png) [General start page](https://trello.com/c/S6DrxJEr/364-general-start-page)

2022-02-07 08:46 UTC, hedgehog1833 requested changes
Suuuper cool, thank you! I have a few comments on the tests, but if you want to bring this live first, I'm also fine with it 👍 Only the changes on the index.html should be done before merging.

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/web/controller/rest/AuthenticationRestControllerTest.java
> +    response.statusCode(OK.value());
```suggestion
    response.status(OK);
```
Like in line 57 ;)

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/web/controller/rest/DashboardRestControllerIT.java
> +  }
And maybe a test that anonymous users cannot access this endpoint?

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/web/controller/rest/DashboardRestControllerTest.java
> +  private RestAssuredMockMvcUtils dashboardRestAssuredMockMvcUtils;
Just `restAssuredUtils` would be enough ;)

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/web/controller/rest/DashboardRestControllerTest.java
> +    dashboardRestAssuredMockMvcUtils = new RestAssuredMockMvcUtils(Endpoints.Rest.DASHBOARD);
As you were so diligent about it in this PR: static import 😄

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/web/controller/rest/ReleasesRestControllerIT.java
> +    @WithMockUser(roles = "ANONYMOUS")
```suggestion
    @WithAnonymousUser
```
See comment in `ArtistsRestControllerIT`

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/web/controller/rest/ReleasesRestControllerTest.java
> +
```suggestion
```

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/test/java/rocks/metaldetector/web/controller/rest/ReleasesRestControllerIT.java
> +  }
And also maybe tests that anonymous users cannot access for example PUT on RELEASES endpoint? Just like for the standard user.

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/main/resources/templates/frontend/index.html
> +                            I wanted to solve this problem once and for all.
```suggestion
                            As I have never been keen on social media, finding out about new releases of my favorite bands has always
                            been a messy, time-consuming task of browsing various sites with huge ugly tables, seeing the same releases
                            again and again. There was no way of tailoring that to my listening habits. Seeing lots of friends having
                            the same problem as Daniel and me, I wanted to solve this once and for all and also give something back to
                            the amazing community.
```

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/main/resources/templates/frontend/index.html
> +                            recently and soon released albums.
```suggestion
                            recent and upcoming albums.
```

2022-02-07 08:46 UTC, hedgehog1833 commented on webapp/src/main/resources/templates/frontend/index.html
> +                            stay up to date when a new album is coming out.
```suggestion
                            stay up to date when a new album is issued.
```
"Coming out" sounds like very German translation. Also this can be misunderstood quite funnily 😉

2022-02-08 09:23 UTC, hedgehog1833 approved these changes
🥇 💪

2022-02-10 16:38 UTC, hedgehog1833 approved these changes

2022-02-10 16:38 UTC, hedgehog1833 commented on webapp/src/main/java/rocks/metaldetector/web/controller/mvc/PreviewIndexController.java
> +  @GetMapping({Endpoints.Frontend.INDEX, Endpoints.Frontend.HOME})
Static imports :)

2022-02-10 16:38 UTC, hedgehog1833 commented on webapp/src/main/java/rocks/metaldetector/web/controller/mvc/IndexController.java
> +  @GetMapping({Endpoints.Frontend.INDEX, Endpoints.Frontend.HOME})
Static imports :)

2022-02-10 16:45 UTC, merged